### ISSUE TITLE
Document when coercion happens in the validation sequence

### ISSUE THREAD

**Issue by koterpillar** [keithasaurus/koda-validate#29]
[Processors](https://koda-validate.readthedocs.io/en/stable/philosophy/processors.html) documentation says:

> [Processor](https://koda-validate.readthedocs.io/en/stable/api/koda_validate.html#koda_validate.Processor)s are most useful after type validation, but before predicates are checked.

However, [Coercion](https://koda-validate.readthedocs.io/en/stable/philosophy/coercion.html#coercion) documentation doesn't tell me when is coercion performed - before the type validation inherent to a particular validator, after or instead of it.

As someone new to Koda, I'd like to have:
* A diagram/list of stages a value passes through while being validated. Example:
  - Coercers are called, if any
  - Built-in validation is performed on the type
  - Processors are called, if any
  - Predicates are called, if any
* For every step of the process (Coercion, Processors, etc.) explicitly say when are they called. Example:
  - Processors are ~most useful~ *called* after type validation, but before predicates.
  - Predicates are called after the value is validated to be of a particular type (the predicates page has this already!)
  - Coercers are called ~before~ ~instead of~ ~after~ *IDK?* type validation the Validator normally does.

**Comment by keithasaurus** [comment]
Thanks. I'll think about how to better message this. What the statement about processors is trying to convey is that if you write your own `Validator`s, you are free to use `Processor`s; or not, but if you do it usually makes sense after you've established the type.

One of the ideas of Koda Validate is that the built-in validators largely adhere to the same form, but they don't always -- not arbitrarily, but because it doesn't always make sense. So unfortunately, it's not possible at present to say how all built-in `Validator`s behave universally. I understand why that might not be intuitive, so I need to figure out how to cover it better.
